XmlFilesManager/Models/Error.cs
namespace XmlFilesManager.Models
{
    public class Error
    {
        public string Message { get; set; }
    }
}

XmlFilesManager/Models/File.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using XmlFilesManager.Helpers;

namespace XmlFilesManager.Models
{
    public class File : IValidatableObject
    {
        [Key]
        public int Id { get; set; }
        public string Version { get; set; }
        public string Name { get; set; }
        public DateTime LastChange { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (!FileNameValidator.IsValid(Name))
            {
                yield return new ValidationResult("Неверный формат имени файла");
            }
        }
    }
}

XmlFilesManager/Models/Log.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace XmlFilesManager.Models
{
    public class Log
    {
        [Key]
        public int Id { get; set; }
        public int FileId { get; set; }
        public DateTime ChangeTime { get; set; }
        public string Action { get; set; }
    }
}

XmlFilesManager/Models/XmlFilesContext.cs
using System.Data.Entity;

namespace XmlFilesManager.Models
{
    public class XmlFilesContext : DbContext
    {
        public DbSet<File> Files { get; set; }
        public DbSet<Log> Logs { get; set; }
    }
}

XmlFilesManager/Controllers/FilesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using XmlFilesManager.Helpers;
using XmlFilesManager.Models;

namespace XmlFilesManager.Controllers
{
    public class FilesController : Controller
    {
        private readonly XmlFilesContext _db = new XmlFilesContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View(_db.Files.ToList());
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return View("Index");
            }
            var file = _db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }

        [HttpGet]
        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            var fileName = upload?.FileName;
            if (!FileNameValidator.IsValid(fileName))
            {
                return View();
            }

            var parsedFile = XmlFileParser.Parse(upload);

            if (parsedFile != null)
            {
                _db.Files.Add(parsedFile);
                _db.SaveChanges();

                new LogsController().AddCreationLog(parsedFile.Id);

                return RedirectToAction("Details", "Files", new {id = parsedFile.Id});
            }

            return View();
        }

        [HttpGet]
        public ActionResult Download(int? id)
        {
            var file = _db.Files.Find(id);

            if (file == null)
            {
                return null;
            }

            var xmlFile = XmlFileParser.GetXml(file);

            new LogsController().AddDownloadingLog(file.Id);

            Response.Clear();
            Response.AddHeader("Content-Disposition", "attachment; filename="+ HttpUtility.UrlEncode(file.Name, Encoding.UTF8));
            Response.ContentType = "text/csv";
            xmlFile.Save(Response.OutputStream);
            Response.End();
            
            return null;
        }

        [HttpPost]
        public ActionResult GetPreview()
        {
            if (Request.Files.Count != 1)
            {
                return View("Error", new Error {Message = "Неверное количество файлов"});
            }

            var postFile = Request.Files["uploadedFile"];

            if (postFile == null)
            {
                return null;
            }

            if (!FileNameValidator.IsValid(postFile.FileName))
            {
                return View("Error", new Error { Message = "Неверный формат имени файла" });
            }

            var parsedFile = XmlFileParser.Parse(postFile);
            return 
                parsedFile == null 
                ? View("Error", new Error { Message = "Неправильная структура файла" })
                : View("Preview", parsedFile);
        }
        
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return View("Index");
            }
            var file = _db.Files.Find(id);
            if (file == null)
            {
                return HttpNotFound();
            }
            return View(file);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Version,Name,LastChange")] File file)
        {
            if (ModelState.IsValid)
            {
                var oldFile = _db.Files.AsNoTracking().First(f => f.Id == file.Id);
                var differences = GetDifferences(oldFile, file);
                new LogsController().AddEditionLog(differences, file.Id);

                file.LastChange = DateTime.Now;
                _db.Entry(file).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(file);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _db.Dispose();
            }
            base.Dispose(disposing);
        }

        private IEnumerable<Difference> GetDifferences(File oldFile, File newFile)
        {
            var differences = new List<Difference>();

            if (!oldFile.Name.Equals(newFile.Name))
            {
                differences.Add(new Difference("Name", oldFile.Name, newFile.Name));
            }
            if (!oldFile.Version.Equals(newFile.Version))
            {
                differences.Add(new Difference("Version", oldFile.Version, newFile.Version));
            }

            return differences;
        }
    }
}

XmlFilesManager/Controllers/LogsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using XmlFilesManager.Helpers;
using XmlFilesManager.Models;

namespace XmlFilesManager.Controllers
{
    public class LogsController : Controller
    {
        private readonly XmlFilesContext _db = new XmlFilesContext();

        [HttpGet]
        public ActionResult Index(int? fileId)
        {
            if (fileId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var file = _db.Files.Find(fileId);
            ViewBag.FileName = file?.Name;
            ViewBag.FileId = fileId;

            var logs = _db.Logs.Where(l => l.FileId == fileId);
            return View(logs.ToList());
        }

        public void AddCreationLog(int fileId)
        {
            var log = new Log
            {
                FileId = fileId,
                Action = GetCreationAction(),
                ChangeTime = DateTime.Now
            };
            _db.Logs.Add(log);
            _db.SaveChanges();
        }

        public void AddEditionLog(IEnumerable<Difference> differences, int fileId)
        {
            foreach (var difference in differences)
            {
                var log = new Log
                {
                    FileId = fileId,
                    Action = GetEditionAction(difference),
                    ChangeTime = DateTime.Now
                };
                _db.Logs.Add(log);
            }
            _db.SaveChanges();
        }

        public void AddDownloadingLog(int fileId)
        {
            var log = new Log
            {
                FileId = fileId,
                Action = GetDownloadingAction(),
                ChangeTime = DateTime.Now
            };
            _db.Logs.Add(log);
            _db.SaveChanges();
        }

        private string GetCreationAction()
        {
            return "Файл сохранен в базу";
        }

        private string GetEditionAction(Difference difference)
        {
            return
                $"'{difference.FieldName}' field changed: old value - '{difference.OldValue}', new value - '{difference.NewValue}'";
        }

        private string GetDownloadingAction()
        {
            return "Файл был скачан";
        }
    }
}

XmlFilesManager/Views/Files/Details.cshtml
@model XmlFilesManager.Models.File

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Информация о файле</h2>

<div>
    <div>
        @Html.ActionLink("История изменений", "Index", "Logs", new {fileId = Model.Id}, null)
    </div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastChange)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastChange)
        </dd>

    </dl>
</div>
<p>
    <a class="btn btn-default" href="@Url.Action("Index", "Files")">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Назад
    </a>
    <a class="btn btn-default" href="@Url.Action("Download", "Files", new {id = Model.Id})">
        <span class="glyphicon glyphicon-arrow-down"></span>
        Скачать
    </a>
    @*@Html.ActionLink("Скачать", "Download", new {id = Model.Id}, new {@class = "btn btn-default"})*@
    @Html.ActionLink("Изменить", "Edit", new {id = Model.Id}, new {@class = "btn btn-warning"})
</p>

XmlFilesManager/Views/Files/Edit.cshtml
@model XmlFilesManager.Models.File

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Изменить</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Version, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Version, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Version, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a class="btn btn-default" href="@Url.Action("Details", "Files", new { id = Model.Id })">
        <span class="glyphicon glyphicon-arrow-left"></span>
        Назад
    </a>
</div>

XmlFilesManager/Views/Files/Index.cshtml
@model IEnumerable<XmlFilesManager.Models.File>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Список файлов</h2>

<p>
    <a class="btn btn-default" href="@Url.Action("Upload")">
        <span class="glyphicon glyphicon-plus"></span>
        Загрузить файл
    </a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Version)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastChange)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Version)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastChange)
        </td>
        <td>
            @Html.ActionLink("Изменить", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
            @Html.ActionLink("Просмотр", "Details", new { id=item.Id }, new { @class = "btn btn-info" })
        </td>
    </tr>
}

</table>

XmlFilesManager/Views/Files/Preview.cshtml
@model XmlFilesManager.Models.File

@{
    Layout = null;
}

<table class="table table-bordered table-condensed">
    <tr>
        <th>Версия</th>
        <td>@Html.DisplayFor(model => model.Version)</td>
    </tr>
    <tr>
        <th>Название</th>
        <td>@Html.DisplayFor(model => model.Name)</td>
    </tr>
    <tr>
        <th>Дата изменения</th>
        <td>@Html.DisplayFor(model => model.LastChange)</td>
    </tr>
</table>

XmlFilesManager/Views/Files/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Home/_Layout.cshtml";
}

<h2>Загрузить файл</h2>

@using (Html.BeginForm("Upload", "Files", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <input type="file" name="upload" id="uploadFile"/>
        <div class="preview"></div>
    </div>
    <input class="btn btn-success" type="submit" value="Загрузить" />
    @Html.ActionLink("Отмена", "Index", "Files", new { @class = "btn btn-default" })
}

<script>
$().ready(function() {
    $("#uploadFile").change(function() {
        var files = document.getElementById('uploadFile').files;
        if (files.length !== 1 || window.FormData === undefined) {
            return;
        }

        var data = new FormData();
        data.append('uploadedFile', files[0]);

        $.ajax({
            url: "/Files/GetPreview",
            type: "POST",
            data: data,
            contentType: false,
            processData: false,
            beforeSend: function() {
                $(".preview").html('<span class="glyphicon glyphicon-time"></span> Подождите...');
            },
            success: function (result) {
                $(".preview").html(result);
            }
        });
    });
})
</script>

XmlFilesManager/Views/Home/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
</head>

<body>
<nav class="navbar navbar-default">
    @Html.ActionLink("Главная", "Index", "Files", null, new { @class = "navbar-brand" })
    @*@Html.RouteLink("Главная", "Default", new { @class = "navbar-brand" })*@
</nav>
<div class="content-wrapper">
    <div class="content">
        @RenderBody()
    </div>
</div>
</body>
</html>

XmlFilesManager/Views/Logs/Index.cshtml
@model IEnumerable<XmlFilesManager.Models.Log>

@{
    ViewBag.Title = "History";
    Layout = "~/Views/Home/_Layout.cshtml";
    
}

<h2>История изменений файла "@ViewBag.FileName"</h2>

<table class="table">
    <tr>
        <th>
            Время
        </th>
        <th>
            Действие
        </th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ChangeTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Action)
            </td>
        </tr>
    }

</table>

<a class="btn btn-default" href="@Url.Action("Details", "Files", new { id = ViewBag.FileId })">
    <span class="glyphicon glyphicon-arrow-left"></span>
    Назад
</a>